export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  RESULT_NOT_FOUND: "RESULT_NOT_FOUND",
  RESULT_NOT_ABNORMAL: "RESULT_NOT_ABNORMAL",
  RESULT_ITEM_DUPLICATED: "RESULT_ITEM_DUPLICATED",
  TASK_NOT_FOUND: "TASK_NOT_FOUND",
  TASK_DEVICE_MISMATCH: "TASK_DEVICE_MISMATCH",
  DEVICE_NOT_FOUND: "DEVICE_NOT_FOUND",
  HAZARD_NOT_FOUND: "HAZARD_NOT_FOUND",
  DUPLICATE_ACTIVE_HAZARD: "DUPLICATE_ACTIVE_HAZARD",
  HAZARD_NOT_OPEN: "HAZARD_NOT_OPEN",
  HAZARD_NOT_RECTIFIED: "HAZARD_NOT_RECTIFIED",
  NOT_ORIGINAL_INSPECTOR: "NOT_ORIGINAL_INSPECTOR",
  RECTIFY_NOTE_REQUIRED: "RECTIFY_NOTE_REQUIRED",
  IDEMPOTENCY_REPLAYED: "IDEMPOTENCY_REPLAYED"
} as const;
