ERROR_CODES = {
    "AUTH_REQUIRED": "AUTH_REQUIRED",
    "RBAC_DENIED": "RBAC_DENIED",
    "VALIDATION_FAILED": "VALIDATION_FAILED",
    "RATE_LIMITED": "RATE_LIMITED",
    # 隐患闭环业务错误码
    "RESULT_NOT_FOUND": "RESULT_NOT_FOUND",
    "RESULT_ALREADY_SUBMITTED": "RESULT_ALREADY_SUBMITTED",
    "HAZARD_ALREADY_EXISTS": "HAZARD_ALREADY_EXISTS",
    "NORMAL_RESULT_NO_HAZARD": "NORMAL_RESULT_NO_HAZARD",
    "HAZARD_NOT_FOUND": "HAZARD_NOT_FOUND",
    "HAZARD_STATUS_CONFLICT": "HAZARD_STATUS_CONFLICT",
    "RECTIFY_NOTE_REQUIRED": "RECTIFY_NOTE_REQUIRED",
    "NOT_ORIGINAL_INSPECTOR": "NOT_ORIGINAL_INSPECTOR",
    "REVIEW_NOTE_REQUIRED": "REVIEW_NOTE_REQUIRED",
    "DEVICE_NOT_FOUND": "DEVICE_NOT_FOUND",
    "INVALID_RESULT_STATUS": "INVALID_RESULT_STATUS",
    "INVALID_SEVERITY": "INVALID_SEVERITY",
    "DEADLINE_REQUIRED": "DEADLINE_REQUIRED",
    "HAZARD_CLOSED": "HAZARD_CLOSED"
}
